# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Carousel
  description: Renders a carousel with images and captions
  icon: view_carousel
  image: /uploads/components/carousel_item.preview.png
  tags:
    - Carousel

# Defines the structure of this component, as well as the default values
blueprint:
  items: [bookshop:carousel_item]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
