---
title: Hogar Albergue para Niños Jesús de Nazaret
timezone: UTC
collections:
  carousel_highlights:
    title: Carousel Highlights
    output: false
  noticias:
    title: Noticias
    output: true
    permalink: "/es/noticias/:name"
  posts:
    title: Posts
    output: true
  proximos_eventos:
    title: Proximos Eventos
    output: true
    permalink: "/es/proximos_eventos/:name"
  upcoming_events:
    title: Upcoming Events
    output: true
    permalink: "/en/upcoming_events/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: noticias
  values:
    layout: noticia
url: https://www.hogarjesusdenazaret.org
permalink: "/:path/"
sass:
  style: compressed
  sass_dir: _sass
feed:
  collections:
    noticias:
      path: "/noticias.xml"
    upcoming_events:
      path: "/upcoming_events.xml"
    proximos_eventos:
      path: "/proximos_eventos.xml"
keep_files:
- uploads
- sw.js
repository: jnewcs/hogar-nazaret
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
