collections_config:
  noticias:
    sort:
      key: date
    add_options:
      - name: Add Noticia for Spanish Site
        editor: content
    schemas:
      default:
        path: schemas/noticia.md
        _enabled_editors:
          - visual
          - content
          - data
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.date:
            label: Publish Date
            allow_empty: false
          $.header_layout:
            type: select
            label: Page header layout
            comment: "There are currently three options: side_by_side, central_title, and flyer. The side_by_side layout includes the post's title on the left with the banner image to the right. The central_title layout just has the post's title with the published date below it. The flyer layout includes the banner image followed by the event’s title and the timing information (day of the week, date, and time)."
            options:
              values:
                - central_title
                - side_by_side
                - flyer
              allow_create: false
              allow_empty: false
          $.banner_image:
            label: Preview Image
            comment: This image is used in list view and certain layouts like the `side_by_side` layout
            type: image
            allow_empty: true
          $.banner_image_alt:
            label: Banner image description
            comment: Adding a description benefits visually impaired users who use screen readers when browsing. Should be written in Spanish
            allow_empty: true
          $.banner_image_style:
            label: Banner image style
            type: select
            options:
              values:
                - cover
                - contain
              allow_create: false
              allow_empty: false
          $.has_photo_grid:
            label: Show Photo Grid
            type: switch
          $.photo_grid:
            label: Multiple Photo Grid
            comment: Displayed underneath the post content
            type: array
            allow_empty: true
          $.photo_grid[*]:
            label: Photo
            type: image
            allow_empty: false
          $.lang_ref:
            label: Identifier to link article to English equivalent
            allow_empty: true

  posts:
    sort:
      key: date
    add_options:
      - name: Add News Article for English Site
        editor: content
    schemas:
      default:
        path: schemas/post.md
        _enabled_editors:
          - visual
          - content
          - data
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.date:
            label: Publish Date
            allow_empty: false
          $.header_layout:
            type: select
            label: Page header layout
            comment: "There are currently three options: side_by_side, central_title, and flyer. The side_by_side layout includes the post's title on the left with the banner image to the right. The central_title layout just has the post's title with the published date below it. The flyer layout includes the banner image followed by the event’s title and the timing information (day of the week, date, and time)."
            options:
              values:
                - central_title
                - side_by_side
                - flyer
              allow_create: false
              allow_empty: false
          $.banner_image:
            label: Preview Image
            comment: This image is used in list view and certain layouts like the `side_by_side` layout
            type: image
            allow_empty: true
          $.banner_image_alt:
            label: Banner image description
            comment: Adding a description benefits visually impaired users who use screen readers when browsing. Should be written in English
            allow_empty: true
          $.banner_image_style:
            label: Banner image style
            type: select
            options:
              values:
                - cover
                - contain
              allow_create: false
              allow_empty: false
          $.has_photo_grid:
            label: Show Photo Grid
            type: switch
          $.photo_grid:
            label: Multiple Photo grid
            comment: Displayed underneath the post content
            type: array
            allow_empty: true
          $.photo_grid[*]:
            label: Photo
            type: image
            allow_empty: false
          $.lang_ref:
            label: Identifier to link article to Spanish equivalent
            allow_empty: true

  carousel_highlights_es:
    name: Carousel Highlights
    sort:
      key: creation_date
    add_options:
      - name: Add Carousel Highlight for Spanish Site
        editor: visual
    disable_add_folder: true
    path: _carousel_highlights/es/
    schemas:
      default:
        path: schemas/carousel_highlights_es.md
        _enabled_editors:
          - visual
          - content
          - data
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.creation_date:
            label: Publish Date
            allow_empty: false

  carousel_highlights_en:
    name: Carousel Highlights
    sort:
      key: creation_date
    add_options:
      - name: Add Carousel Highlight for English Site
        editor: visual
    disable_add_folder: true
    path: _carousel_highlights/en/
    schemas:
      default:
        path: schemas/carousel_highlights_en.md
        _enabled_editors:
          - visual
          - content
          - data
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.creation_date:
            label: Publish Date
            allow_empty: false

collection_groups:
  - heading: "Spanish Website"
    collections:
      - noticias
      - carousel_highlights_es
  - heading: "English Website"
    collections:
      - posts
      - carousel_highlights_en
