collections_config:
  noticias:
    sort:
      key: date
    schemas:
      default:
        path: schemas/noticia.md
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.date:
            label: Publish Date
            allow_empty: false
          $.header_layout:
            type: select
            options:
              values:
                - central_title
                - side_by_side
                - flyer
              allow_empty: false
          $.lang_ref:
            label: Identifier to link article to English equivalent
            allow_empty: true

  posts:
    sort:
      key: date
    add_options:
      - name: Add News Article for English Site
        editor: visual
    schemas:
      default:
        path: schemas/post.md
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.date:
            label: Publish Date
            allow_empty: false
          $.header_layout:
            type: select
            options:
              values:
                - central_title
                - side_by_side
                - flyer
              allow_empty: false
          $.lang_ref:
            label: Identifier to link article to Spanish equivalent
            allow_empty: true

collection_groups:
  - heading: "Spanish Website"
    collections:
      - noticias
  - heading: "English Website"
    collections:
      - posts
