collections_config:
  noticias:
    sort:
      key: date
    add_options:
      - name: Add Noticia for Spanish Site
        editor: content
    _enabled_editors:
      - visual
      - data
    schemas:
      default:
        path: schemas/noticia.md
        hide_extra_inputs: true
        _inputs:
          $.date:
            label: Publish Date
            allow_empty: false
          $.banner_image:
            label: Preview Image
            comment: This image is used for aggregate views (Noticias page)
            type: image
            allow_empty: true
          $.banner_image_alt:
            label: Preview image description
            comment: Adding a description benefits visually impaired users who use screen readers when browsing. Should be written in Spanish
            allow_empty: true
          $.banner_image_style:
            label: Preview image style
            type: select
            options:
              values:
                - cover
                - contain
              allow_create: false
              allow_empty: false
          $.content_blocks:

  posts:
    sort:
      key: date
    add_options:
      - name: Add News Article for English Site
        editor: content
    _enabled_editors:
      - visual
      - data
    schemas:
      default:
        path: schemas/post.md
        hide_extra_inputs: true
        _inputs:
          $.date:
            label: Publish Date
            allow_empty: false
          $.banner_image:
            label: Preview Image
            comment: This image is used for aggregate views (News page)
            type: image
            allow_empty: true
          $.banner_image_alt:
            label: Preview image description
            comment: Adding a description benefits visually impaired users who use screen readers when browsing. Should be written in English
            allow_empty: true
          $.banner_image_style:
            label: Preview image style
            type: select
            options:
              values:
                - cover
                - contain
              allow_create: false
              allow_empty: false
          $.content_blocks:

  carousel_highlights_es:
    name: Carousel Highlights
    sort:
      key: creation_date
    add_options:
      - name: Add Carousel Highlight for Spanish Site
        editor: visual
    _enabled_editors:
      - visual
      - data
    disable_add_folder: true
    path: _carousel_highlights/es/
    schemas:
      default:
        path: schemas/carousel_highlights_es.md
        hide_extra_inputs: true
        _inputs:
          $.creation_date:
            label: Publish Date
            allow_empty: false

  content_blocks_page_en:
    name: English Pages
    disable_add_folder: true
    disable_add: true
    path: en/
    _enabled_editors:
      - visual
      - data
    schemas:
      default:
        path: schemas/content_blocks_page_en.md
        hide_extra_inputs: true

collection_groups:
  - heading: "Spanish Website"
    collections:
      - noticias
      - carousel_highlights_es
  - heading: "English Website"
    collections:
      - posts
      - content_blocks_page_en

_inputs:
  $.lang:
    hidden: true
  $.redirect_from:
    hidden: true
  $.layout:
    hidden: true
  $.lang_ref:
    label: Identifier to link page to English/Spanish equivalent
    allow_empty: true
