collections_config:
  noticias:
    sort:
      key: date
    schemas:
      default:
        path: schemas/noticia.md
        _enabled_editors:
          - visual
          - content
          - data
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.date:
            label: Publish Date
            allow_empty: false
          $.header_layout:
            type: select
            label: Page layout
            options:
              values:
                - central_title
                - side_by_side
                - flyer
              allow_empty: false
          $.banner_image:
            label: Preview Image (used in list view and certain layouts)
            type: image
            allow_empty: true
          $.photo_grid:
            label: Photo grid
            type: array
            structures:
              - value:
                type: image
          $.lang_ref:
            label: Identifier to link article to English equivalent
            allow_empty: true

  posts:
    sort:
      key: date
    add_options:
      - name: Add News Article for English Site
        editor: visual
    schemas:
      default:
        path: schemas/post.md
        _enabled_editors:
          - visual
          - content
          - data
        hide_extra_inputs: true
        _inputs:
          $.lang:
            hidden: true
          $.date:
            label: Publish Date
            allow_empty: false
          $.header_layout:
            type: select
            label: Page layout
            options:
              values:
                - central_title
                - side_by_side
                - flyer
              allow_empty: false
          $.banner_image:
            label: Preview Image (used in list view and certain layouts)
            type: image
            allow_empty: true
          $.photo_grid:
            label: Photo grid
            type: array
            structures:
              - value:
                type: image
          $.lang_ref:
            label: Identifier to link article to Spanish equivalent
            allow_empty: true

collection_groups:
  - heading: "Spanish Website"
    collections:
      - noticias
  - heading: "English Website"
    collections:
      - posts
