collections_config:
  noticias:
    schemas:
      default:
        path: schemas/noticia.md
        hide_extra_inputs: true
  posts:
    add_options:
      - name: Add English Post
        editor: visual
    schemas:
      default:
        path: schemas/post.md
        hide_extra_inputs: true
