source "https://rubygems.org"

gem "jekyll", '~> 4.4.1'

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-tagging"
  gem "jekyll-archives"
  gem "jekyll-redirect-from"
  gem "jekyll-sitemap"
  gem "jekyll-bookshop", "3.4.1"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
