# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content
  description: Generic rich content area. Use this component to add text, images, and other HTML content.
  icon: wysiwyg
  image: /uploads/components/content.preview.png
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  content_html: ""
  show_container: true
  text_alignment: left
  background_color: white

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content_html: <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>

picker_preview:
  text: Content # Used in a picker
  subtext: false # Disables the subtext in the picker

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  show_container:
    type: checkbox
    comment: When toggled on, default padding appears around the content
  text_alignment:
    type: select
    label: Text Alignment
    options:
      values:
        - left
        - centered
        - right
      allow_create: false
      allow_empty: false
  background_color:
    type: select
    label: Background color
    options:
      values:
        - white-ter
        - white
      allow_create: false
      allow_empty: false
