# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content
  description: Generic rich content area
  icon: wysiwyg
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  content_html: ""
  show_container: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content_html: <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>

picker_preview:
  text: Content # Used in a picker
  subtext: false # Disables the subtext in the picker

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  show_container:
    type: checkbox
    comment: When toggled on, default padding appears around the content
