# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Board Profile
  description: Renders a board profile
  icon: person
  tags:
    - Board

# Defines the structure of this component, as well as the default values
blueprint:
  name: "Board Person #1"
  city: San Juan
  tag_style: primary
  position: Vice President
  background: "A resident of the City of Mayagüez. She has served on the Board for a year"
  reason: "To give back all the good things God has given me by helping to educate children"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name:
    type: text
    allow_empty: false
  city:
    type: text
    allow_empty: false
  tag_style:
    type: select
    options:
      values:
        - primary
        - secondary
        - light
      allow_create: false
      allow_empty: false
  is_leader:
    type: checkbox
    label: "Leadership position on the board?"
    allow_empty: false
  position:
    type: text
    label: Position on the Board
    allow_empty: false
  background:
    type: text
    label: Background (profressional, etc.)
    allow_empty: true
  reason:
    type: text
    label: Reason for joining the Board
    allow_empty: true
