# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Simple Header
  description: Header with an optional date subtitle
  image: /uploads/components/simple_header.preview.png
  icon: wysiwyg
  tags:
    - Header

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Page Title"
  title_alignment: "left"
  show_padding_top: true
  show_padding_bottom: true
  date: null
  background_color: "white-ter"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: Title is left aligned
    type: text
    allow_empty: false
  title_alignment:
    type: select
    label: Title alignment
    options:
      values:
        - left
        - centered
        - right
      allow_create: false
      allow_empty: false
  show_padding_top:
    type: switch
  show_padding_bottom:
    type: switch
  date:
    allow_empty: true
  background_color:
    type: select
    label: Background color
    options:
      values:
        - white-ter
        - white
      allow_create: false
      allow_empty: false
