# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Flyer Header
  description: Header with a large central image that can be expanded into a modal
  image: /uploads/components/flyer_header.preview.png
  icon: article
  tags:
    - Header

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Page Title"
  date: 2020-07-15T12:00:00.000Z
  time: "10 AM - 2 PM"
  image: "https://hogarjesusdenazaret.org/uploads/page_header_images/hogar_playground.jpg"
  image_alt: "Image description"
  image_height: 350
  hide_call_to_action: false
  call_to_action:
    text: "Buy Tickets"
    url: "https://www.eventbrite.com/e/337606900327"
  location:
    text: "University of Puerto Rico at Mayagüez"
    url: "https://goo.gl/maps/NC4cC7QhTLYcn5hUA"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: Centered aligned on the page
    type: text
    allow_empty: false
  hide_date:
    type: switch
    label: "Hide the date text?"
    comment: When toggled, the header will hide date text
    allow_empty: false
  date:
    type: datetime
    comment: "Date to display in readable format (e.g Domingo 12 de junio de 2022)"
    allow_empty: true
    hidden: hide_date
  hide_time:
    type: switch
    label: "Hide the time text?"
    comment: When toggled, the header will hide time text
    allow_empty: false
  time:
    type: text
    comment: Specific time that displays underneath the date. Can be blank
    allow_empty: true
    hidden: hide_time
  location:
    type: object
    allow_empty: true
    options:
      text:
        type: text
        label: Text shown in `location` button
      url:
        type: url
        label: URL for `location` button
  image:
    type: image
    label: Image
    comment: Displayed centered on top of the title
    allow_empty: false
  image_alt:
    type: text
    label: Image description
    comment: Adding a description benefits visually impaired users who use screen readers when browsing the site
    allow_empty: true
  image_height:
    label: Height of the image in pixels
    type: number
    min: 0
    allow_empty: false
  hide_call_to_action:
    type: switch
    label: "Hide the call to action button?"
    comment: When toggled, the header will hide the call to action button
    allow_empty: false
  call_to_action:
    type: object
    allow_empty: true
    hidden: hide_call_to_action
    options:
      text:
        type: text
        label: Text shown in `call to action` button
      url:
        type: url
        label: URL for `call to action` button
