# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Split Image Content
  description: Generic text component with option to show image to the left/right of content
  icon: vertical_split
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  layout: image_right
  content_html: ""
  image: null

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content_html: <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  layout:
    comment: Select the layout for the image in relation to the content
    type: select
    options:
      values:
        - image_left
        - image_right
  content_html:
    type: html
    label: Content Text
    allow_empty: false
  image:
    type: image
    label: Image
    comment: Displayed to the right of the content provided
    allow_empty: true
  image_alt:
    type: text
    label: Image description
    comment: Adding a description benefits visually impaired users who use screen readers when browsing the site
