# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content Highlights
  description: Component to render text and HTML highlights in a single row
  icon: wysiwyg
  image: /uploads/components/content_highlights.preview.png
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: white
  highlights: [bookshop:content_highlight]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background_color:
    type: select
    label: Background color
    options:
      values:
        - white-ter
        - white
      allow_create: false
      allow_empty: false
