# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content Highlights
  description: Header with a blurred image and centered title
  icon: wysiwyg
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  highlights: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  highlights:
    type: array
    structures:
      - value:
        title: Some Title
        content_html: '<p>Highlight description</p>'
      _inputs:
        title:
          type: text
          label: Highlight Title
          allow_empty: false
        content_html:
          type: html
          label: Highlight Text
          allow_empty: false
