# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Blur Header
  description: Header with a blurred image and centered title
  icon: blur_on
  image: /uploads/components/blur_header.preview.png
  tags:
    - Header

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Page Title"
  title_alignment: "centered"
  title_color: "#2E333D"
  image: null
  image_style: cover

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: You can customize the text alignment and color
    type: text
    allow_empty: false
  title_color:
    comment: The default purple color is `#1B0278`. A soft black is `#2E333D`. White is `#FFFFFF`
    type: color
    allow_empty: true
  title_alignment:
    type: select
    label: Title alignment
    options:
      values:
        - left
        - centered
        - right
      allow_create: false
      allow_empty: false
  image:
    type: image
  image_alt:
    type: text
    label: Image description
    comment: Adding a description benefits visually impaired users who use screen readers when browsing the site
  image_style:
    type: select
    label: Image style
    options:
      values:
        - cover
        - contain
      allow_create: false
      allow_empty: false
