---
label: default
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: lang_ref
  type: text
  config:
    required: false
  label: lang_ref
- type: text
  name: layout
  label: layout
  hidden: true
  default: page
- name: lang
  type: text
  config:
    required: false
  label: lang
  hidden: true
  default: en
