# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Side by Side Header
  description: Header with an image to the right
  icon: vertical_split
  tags:
    - Header

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Page Title"
  date: 2024-07-15T12:00:00.000Z
  hide_date: false
  image: "https://hogarjesusdenazaret.org/uploads/page_header_images/hogar_playground.jpg"
  image_alt: 'Image description'
  image_style: contain

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: Title is set to the left of the image
    type: text
    allow_empty: false
  hide_date:
    type: switch
    label: "Hide the date text?"
    comment: When toggled, the header will hide date text
    allow_empty: false
  date:
    type: datetime
    comment: "Date to display in readable format (e.g Domingo 12 de junio de 2022)"
    allow_empty: true
    hidden: hide_date
  image:
    type: image
    label: Image
    comment: Displayed to the right of the title
    allow_empty: false
  image_alt:
    type: text
    label: Image description
    comment: Adding a description benefits visually impaired users who use screen readers when browsing the site
    allow_empty: true
  image_style:
    label: Image style
    type: select
    options:
      values:
        - cover
        - contain
      allow_create: false
      allow_empty: false
